### PR TITLE
HUS-312 Update checkbox CSS to fix jump to top

### PR DESCRIPTION
**Pull request by sourovroy**
Add `position: relative;` to `.hustle-checkbox`

### CODE REVIEW

**Comment by a-danae** [comment]
@sourovroy Before reviewing the actual fix, would you please exclude the compiled files from the PR? Those are package-json.lock, and the two minified files.

**Comment by a-danae** [comment]
@iamleigh passing this to you to review

**Review by iamleigh — APPROVED** [review]
@a-danae PR looks fine but changelog info is missing.

**Review by iamleigh — CHANGES_REQUESTED** [review]
@sourovroy changelog information is missing.

**Review by iamleigh — APPROVED** [review]

**Pull request merged**
